org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)

neo_version=21.1.219
neo_version_range=[21,)

loader_version_range=[4,)

neoForge.parchment.minecraftVersion=1.21.1
neoForge.parchment.mappingsVersion=2024.11.17

create_version=6.0.10-280
ponder_version=1.0.82
flywheel_version=1.0.6
jei_minecraft_version=1.21.1
jei_version=19.25.0.322
tfmg_version=1.2.2

mod_id=tfmgtweaks
mod_name=Create: The Factory Must WORK
mod_archive_name=TFMW
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.tfmgtweaks
mod_authors=Fluffy_Commando
mod_description=A large collection of bug fixes and new content for Create: The Factory Must Grow, including a reworked oil extraction chain, a new Boiler multiblock, and a substantial number of upstream TFMG bug fixes
